on:
  push:
    branches:
      # Para ativar a compilação e publicação de aplicativo colocar APK como  branch
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build app
        run: eas build -p android --profile apk --non-interactive --local
      - name: Subir APK para outro repo
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          GIT_ASKPASS: /bin/true
          GIT_AUTHOR_NAME: "kayqueh"
          GIT_AUTHOR_EMAIL: "kayque@brcore.com.br"
          GIT_COMMITTER_NAME: "kayqueh"
          GIT_COMMITTER_EMAIL: "kayque@brcore.com.br"
        run: |
          git clone https://$GITHUB_TOKEN@github.com/kayqueh/populate-apks.git
          cd populate-apks
          git checkout main
          cp /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/build-*.apk ${{ github.event.repository.name }}-$(date +"%Y-%m-%d_%H-%M-%S").apk
          git add .
          git commit -m "Novo APK"
          git push --force https://$GITHUB_TOKEN@github.com/kayqueh/populate-apks.git
