on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Trabalho sujo
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          GIT_ASKPASS: /bin/true
          GIT_AUTHOR_NAME: "kayqueh"
          GIT_AUTHOR_EMAIL: "kayque@brcore.com.br"
          GIT_COMMITTER_NAME: "kayqueh"
          GIT_COMMITTER_EMAIL: "kayque@brcore.com.br"
        run: |
          git clone -b main https://$GITHUB_TOKEN@github.com/kayqueh/populate-app.git
          git clone https://$GITHUB_TOKEN@github.com/kayqueh/populate-will-eletro.git temp_folder
          cd populate-app
          git rm assets/icone.png
          git rm assets/icone2.png
          git rm app.json
          git rm eas.json
          git rm google-services.json
          git commit -m "Remove arquivos"
          cp ../temp_folder/assets/icone.png .
          cp ../temp_folder/assets/icone2.png .
          cp ../temp_folder/app.json .
          cp ../temp_folder/eas.json .
          cp ../temp_folder/google-services.json .
          git add .
          git commit -m "Adicionar arquivos"
          git push --force https://$GITHUB_TOKEN@github.com/kayqueh/populate-will-eletro.git main:main
