on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Preparar ambiente
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          GIT_ASKPASS: /bin/true
          GIT_AUTHOR_NAME: "kayqueh"
          GIT_AUTHOR_EMAIL: "kayque@brcore.com.br"
          GIT_COMMITTER_NAME: "kayqueh"
          GIT_COMMITTER_EMAIL: "kayque@brcore.com.br"
        run: |
          git clone -b main https://$GITHUB_TOKEN@github.com/kayqueh/populate-will-eletro.git ${{ github.workspace }}

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install
 
      - name: 🚀 Build app
        run: eas build -p android --profile production --non-interactive --local

      - name: Preparar aab
        run: |
          cp /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/build-*.aab /home/runner/work/cmp.aab
          
      - name: 🚀 Publicar app
        run: eas submit -p android --profile production --path /home/runner/work/cmp.aab
